### ISSUE TITLE
Support for composite metrics

### ISSUE THREAD

**Issue by philmcmahon** [librato/librato-java#26]
This would be awesome.

**Comment by collinvandyck** [comment]
Hi!  You can currently add complex gauges with librato-java:

```
LibratoBatch batch = new LibratoBatch(...)
batch.addMeasurement(
  MultiSampleGaugeMeasurement.builder("metric-name")
    .setSum(sum)
    .setMax(max)
    .setMin(min)
    ....))
batch.post(source)
```

Is that what you were looking for?

**Comment by philmcmahon** [comment]
Sorry, I wrote the title wrong - I mean metrics of type 'composite' with a composite function to go with them. I might be wrong but this didn't seem immediately possible with librato-java.

**Comment by collinvandyck** [comment]
Ah I see. Yes, our current java bindings just support emitting measures for normal metrics. We've long wanted to make a more comprehensive java library. Thanks for the idea -- will keep this open.

**Comment by philmcmahon** [comment]
Just getting round to updating the librato java client in our application - less boilerplate now which is nice! As far as I can tell though there's still no support for composite metrics?

**Comment by mheffner** [comment]
@philmcmahon Yeah, so far this library has been built largely just as a means to publish data to Librato. It's never supported a "read API" to pull data back from Librato.

Can you explain your use case for composites some more? Are you trying to create persisted composites, read data given arbitrary composite expressions or something else?

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/appoptics-api-java.
