### ISSUE TITLE
Instantiation of a Sanitizer

### ISSUE THREAD

**Issue by paulwellnerbou** [librato/librato-java#30]
Hi,

I am trying to use this library to send metrics to librato. The sample code in the documentation seems to be missing the instantiation of the sanitizer:

`LibratoBatch batch = new LibratoBatch(batchSize, sanitizer, timeout, timeoutUnit, agent, poster)`

Looking at the code, it seems that the required sanitizer (`Sanitizer.LAST_PASS`) is always executed, so I suppose, that Sanitizer.NO_OP is expected here?

`LibratoBatch batch = new LibratoBatch(batchSize, SANITIZER.NO_OP, timeout, timeoutUnit, agent, poster)`

That's a bit confusing, although this is a special library for librato, I have to write much more code than expected. Using a third party implementation (like https://github.com/GeoNet/app-server-metrics) which is using just an HTTP client, would lead to easier code:

`sender = new LibratoMetricsSender(libratoUser, libratoApiKey);
sender.send("server", ...);`

Is there a shorter way, like this, to send metrics to librato?
Thanks.

**Comment by collinvandyck** [comment]
Hi @paulwellnerbou, thanks for bringing this up. I'll update the documentation to specify that the NO_OP sanitizer can be used as a default, or, you can also specify your own here if you'd like.

To your other points, yes, this librato is a bit eh, long in the tooth at this point and is in serious need of a remodeling. We'll keep your feedback in mind, many thanks for making the effort to explain your point so clearly.

best

**Comment by collinvandyck** [comment]
@paulwellnerbou also on a side note, are you using dropwizard metrics? If so you may want to look into https://github.com/librato/metrics-librato. Not sure if you've seen that or not. HTH.

**Comment by paulwellnerbou** [comment]
@collinvandyck Thanks for the suggestion. No, I didn't see that. But I am not using dropwizard, I am creating a library to collect specific metrics from any JSON (local file or http address) and send it to Librato (or any other not yet implemented target, like an elastic search instance, DataDog, hosted graphite, ...).
