### ISSUE TITLE
Design discussion in a multithreaded use of LibratoBatch

### ISSUE THREAD

**Issue by paulwellnerbou** [librato/librato-java#32]
Hi there,

in the application I wrote I discovered a memory leak which was caused by too much thread objects called "librato-http-poster". The Problem in this case was that I used my easy way to create the `LibratoBatch` instance with the Builder (see #31), but I did not call `.close()` for the `DefaultHttpPoster`.

It is not possible to use a single `DefaultHttpPoster` for several instances of `LibratoBatch`, because the `DefaultHttpPoster` is not thread safe, so I have to create a new one (and thus, a new `LibratoBatch`) for each few metrics I want to send to librato. That's ok, but this leads to some design issues in code:
- When creating a `LibratoBatch` I don't want to know anything about the underlying implementation. But before creating a `LibratoBatch` now, I have to create a new `DefaultHttpPoster` first, and keep it in memory to be able to close the thread pool after posting.
- When posting the actual metrics with `LibratoBatch`, I have to create a new `LibratoBatch` instance and thus, know about the credentials. This is not the location in code where I want to care about configuration.

Not sure, if I explained this issues clearly enough.

For the moment I work around this closing the `DefaultHttpPoster`, as I am using Groovy this works (although not recommended):

```
libratoBatch.httpPoster.close()
```

There are several possibilities to fix this issues:
1. Make DefaultHttpPoster completely threadsafe, so that it can be reused (as singleton bean)
2. Create a `close()` method (or similar) in `LibratoBatch` which calls `close()` of it's `HttpPoster`
3. Delegate the instantiation and closing of the executor pool to the `post()` method of the `DefaultHttpPoster` (in my eyes this would be the best solution, why should other code care about the internals of the thread implementation of this class?)

**Comment by collinvandyck** [comment]
Hi There,

Sorry, I'm not following how the `DefaultHttpPoster` is not thread safe.  Can you elaborate?

**Comment by paulwellnerbou** [comment]
Hi,

yes, I will try to reproduce it tomorrow. I got concurreny related errors when using it with several threads.

**Comment by collinvandyck** [comment]
Paul,

Please keep in mind that you should really only be instantiating DefaultHttpPoster (or your own implementation) once.  The DefaultHttpPoster creates a single threaded executor to process http requests; it is not meant to be shut down after a request.  

I'm more than happy to work with you on the errors you get from using it in this manner.

best
Collin

**Comment by paulwellnerbou** [comment]
Hi Collin,

sorry for the late reply. Unfortunately I am not able to reproduce the concurrency problem any more, my code changed too much, and now I am using a single instance of each for each thread, so I don't have the concurrency problem any more.

But it seemed to be the LibratoBatch, not the DefaultHttpPoster which caused the concurrency problems.

That the DefaultHttpPoster has to be used as a singleton is an important information, thanks for that, maybe this should be documented in the README (because if not, it will cause a memory leak).

I still don't really like the design as I don't want to care about the implementation of the HttpPoster used by LibratoBatch in my client code. The complexity I would have to add to my code to ensure that the HttpPoster is used as a singleton (but LibratoBatch not!) just to post to librato (which is not for librato only) is much higher than just calling .close() to close the thread pool (avoiding the memory leak, too). For now, there is only one implementation of the HttpPoster interface, but any implementing class should be considered as a singleton. What do you think?

Nevertheless I'll change the pull request for my Builder in a way that it won't create a new DefaultHttPoster each time.

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/appoptics-api-java.
