### ISSUE TITLE
Switch to Jackson under FasterXML namespace

### ISSUE THREAD

**Issue by jcomo** [librato/librato-java#42]
Curious if there is a particular reason for using org.codehaus.jackson instead of com.fasterxml.jackson? As far as I know the codehaus groupid was deprecated a long time ago in favor of FasterXML

**Comment by sergeyvladimirovich** [comment]
@jcomo  : upgrading that particular dependency is in our backlog.

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/appoptics-api-java.
