### ISSUE TITLE
Proxy support for LibratoClient

### ISSUE THREAD

**Issue by johannesvogt** [librato/librato-java#44]
Hi,
I am trying to send metrics to librato from an application running behind a firewall. I have to use a http proxy to talk to librato. It seems the LibratoClient does not support proxies at the moment. Is it planned to add that feature in the future?

Thanks!

**Comment by mheffner** [comment]
@johannesvogt I don't believe it supports it directly, but if you provide a customer poster that implements https://github.com/librato/librato-java/blob/master/src/main/java/com/librato/metrics/client/IPoster.java, you can handle the proxying however is best appropriate.

**Comment by johannesvogt** [comment]
Thanks @mheffner . Yes, that's what I saw as well. However, if I don't miss anything the only way to inject an IPoster is via reflection (?)

**Comment by mheffner** [comment]
@johannesvogt You should be able to set on the builder: https://github.com/librato/librato-java/blob/master/src/main/java/com/librato/metrics/client/LibratoClientBuilder.java#L33

**Comment by johannesvogt** [comment]
@mheffner you are right. My problem is actually that I'm using the metrics-librato library (https://github.com/librato/metrics-librato), that doesn't allow setting custom LibratoClients. But that is not in the scope of this project. I would actually need a proxy config option in metric-librato's ReporterBuilder, or at least an option to set a custom LibratoClient. Anyway thanks for looking into it

**Comment by mheffner** [comment]
@johannesvogt Ahh, I see. Yeah, I thought there was a way to override the LibratoClientFactory for the ReporterBuilder, but I don't see one here: https://github.com/librato/metrics-librato/blob/master/src/main/java/com/librato/metrics/reporter/ReporterBuilder.java. This is the default builder, but I don't see a way currently to change it: https://github.com/librato/metrics-librato/blob/master/src/main/java/com/librato/metrics/reporter/DefaultLibratoClientFactory.java.

Maybe a PR to add a custom LibratoClientFactory to ReporterBuilder would be the way to go?

**Comment by johannesvogt** [comment]
@mheffner yes that makes sense. I will have have a look at it

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/appoptics-api-java.
